package de.drtobiasprinz.summitbook.models

import android.widget.TextView
import de.drtobiasprinz.summitbook.databinding.FragmentSummitEntryThirdPartyBinding
import de.drtobiasprinz.summitbook.db.entities.Summit
import de.drtobiasprinz.summitbook.ui.utils.ExtremaValuesSummits

enum class TextFieldGroupThirdParty {
    ThirdParty,
    ThirdPartyAdditionalData,
}

enum class TextFieldThirdParty(
    val group: TextFieldGroupThirdParty,
    val descriptionTextView: (FragmentSummitEntryThirdPartyBinding) -> TextView,
    val valueTextView: (FragmentSummitEntryThirdPartyBinding) -> TextView,
    val unit: String,
    val getValue: (Summit) -> Number?,
    val getMinMaxSummit: (ExtremaValuesSummits?) -> Pair<Summit, Summit>? = { _ -> null },
    val reverse: Boolean = false,
    val toHHms: Boolean = false,
    val digits: Int = 1,
    val factor: Int = 1,
    val valueTextViewRange: (FragmentSummitEntryThirdPartyBinding) -> TextView? = { _ -> null },
    val getValueRange: (Summit) -> Number? = { _ -> null },
) {
    AverageHr(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.averageHrText },
        { b -> b.averageHr },
        "bpm",
        { e -> e.garminData?.averageHR },
        { e -> e?.averageHRMinMax },
        digits = 0,
        reverse = true
    ),
    MaxHr(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.maxHrText },
        { b -> b.maxHr },
        "bpm",
        { e -> e.garminData?.maxHR },
        { e -> e?.maxHRMinMax },
        digits = 0,
        reverse = true
    ),
    Calories(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.caloriesText },
        { b -> b.calories },
        "kcal",
        { e -> e.garminData?.calories },
        { e -> e?.caloriesMinMax },
        digits = 0
    ),
    PartPaved(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.surfaceTypeUnpavedPercentageText },
        { b -> b.surfaceTypeUnpavedPercentage },
        "%",
        { e -> e.garminData?.surfaceTypeUnpavedPercentage },
        { e -> e?.surfaceTypeUnpavedPercentageMinMax },
        digits = 1,
    ),
    AerobicTrainingEffect(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.aerobicTrainingEffectText },
        { b -> b.aerobicTrainingEffect },
        "",
        { e -> e.garminData?.aerobicTrainingEffect },
        { e -> e?.aerobicTrainingEffectMinMax },
    ),
    AnaerobicTrainingEffect(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.anaerobicTrainingEffectText },
        { b -> b.anaerobicTrainingEffect },
        "",
        { e -> e.garminData?.anaerobicTrainingEffect },
        { e -> e?.anaerobicTrainingEffectMinMax },
    ),
    Grit(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.gritText },
        { b -> b.grit },
        "",
        { e -> e.garminData?.grit },
        { e -> e?.gritMinMax },
    ),
    Flow(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.flowText },
        { b -> b.flow },
        "",
        { e -> e.garminData?.flow },
        { e -> e?.flowMinMax },
    ),
    TrainingsLoad(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.trainingLoadText },
        { b -> b.trainingLoad },
        "",
        { e -> e.garminData?.trainingLoad },
        { e -> e?.trainingsLoadMinMax },
    ),
    Vo2Max(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.vo2MaxText },
        { b -> b.vo2Max },
        "",
        { e -> e.garminData?.vo2max },
        { e -> e?.vo2maxMinMax },
        digits = 1
    ),
    Strokes(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.strokesText },
        { b -> b.strokes },
        "",
        { e -> e.garminData?.cyclingDynamics?.totalNumberOfStrokes },
        { e -> e?.strokesMinMax },
        digits = 1
    ),
    StandingTime(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.standingTimeText },
        { b -> b.standingTime },
        "",
        { e -> e.garminData?.cyclingDynamics?.standingTime },
        { e -> e?.standingTimeMinMax },
        digits = 1,
        toHHms = true
    ),
    StandingAvgPower(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.standingAvgPowerText },
        { b -> b.standingAvgPower },
        "",
        { e -> e.garminData?.cyclingDynamics?.averageStandingPower },
        { e -> e?.standingAvgPowerMinMax },
        digits = 0
    ),
    StandingMaxPower(
        TextFieldGroupThirdParty.ThirdParty,
        { b -> b.standingMaxPowerText },
        { b -> b.standingMaxPower },
        "",
        { e -> e.garminData?.cyclingDynamics?.maxStandingPower },
        { e -> e?.standingMaxPowerMinMax },
        digits = 0
    ),
    PedalSmoothness(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.pedalSmoothnessText },
        { b -> b.pedalSmoothnessLeft },
        "%",
        { e -> e.garminData?.cyclingDynamics?.leftPedalSmoothness },
        digits = 1,
        valueTextViewRange = { b -> b.pedalSmoothnessRight },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.rightPedalSmoothness },
    ),
    Balance(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.balanceText },
        { b -> b.balanceLeft },
        "%",
        { e -> e.garminData?.cyclingDynamics?.leftBalance },
        digits = 1,
        valueTextViewRange = { b -> b.balanceRight },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.rightBalance },
    ),
    TorqueEffectiveness(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.torqueEffectivenessText },
        { b -> b.torqueEffectivenessLeft },
        "%",
        { e -> e.garminData?.cyclingDynamics?.leftTorqueEffectiveness },
        digits = 1,
        valueTextViewRange = { b -> b.torqueEffectivenessRight },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.rightTorqueEffectiveness },
    ),
    LeftPowerPhase(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.cyclingDynamicsLeftPowerPhaseText },
        { b -> b.cyclingDynamicsLeftPowerPhaseStart },
        "°",
        { e -> e.garminData?.cyclingDynamics?.leftPowerPhaseStart },
        digits = 1,
        valueTextViewRange = { b -> b.cyclingDynamicsLeftPowerPhaseEnd },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.leftPowerPhaseEnd },
    ),
    RightPowerPhase(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.cyclingDynamicsRightPowerPhaseText },
        { b -> b.cyclingDynamicsRightPowerPhaseStart },
        "°",
        { e -> e.garminData?.cyclingDynamics?.rightPowerPhaseStart },
        digits = 1,
        valueTextViewRange = { b -> b.cyclingDynamicsRightPowerPhaseEnd },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.rightPowerPhaseEnd },
    ),
    LeftPeakPowerPhase(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.cyclingDynamicsLeftPeakPowerPhaseText },
        { b -> b.cyclingDynamicsLeftPeakPowerPhaseStart },
        "°",
        { e -> e.garminData?.cyclingDynamics?.leftPowerPhasePeakStart },
        digits = 1,
        valueTextViewRange = { b -> b.cyclingDynamicsLeftPeakPowerPhaseEnd },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.leftPowerPhasePeakEnd },
    ),
    RightPeakPowerPhase(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.cyclingDynamicsRightPeakPowerPhaseText },
        { b -> b.cyclingDynamicsRightPeakPowerPhaseStart },
        "°",
        { e -> e.garminData?.cyclingDynamics?.rightPowerPhasePeakStart },
        digits = 1,
        valueTextViewRange = { b -> b.cyclingDynamicsRightPeakPowerPhaseEnd },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.rightPowerPhasePeakEnd },
    ),
    PlatformCenterOffset(
        TextFieldGroupThirdParty.ThirdPartyAdditionalData,
        { b -> b.cyclingDynamicsPCOText },
        { b -> b.cyclingDynamicsPCOLeft },
        "mm",
        { e -> e.garminData?.cyclingDynamics?.leftPlatformCenterOffset },
        digits = 1,
        valueTextViewRange = { b -> b.cyclingDynamicsPCORight },
        getValueRange =  { e -> e.garminData?.cyclingDynamics?.rightPlatformCenterOffset },
    ),
}
